apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wordpress
spec:
  interval: 5m
  chart:
    spec:
      chart: wordpress
      version: "23.1.0"
      sourceRef:
        kind: HelmRepository
        name: wordpress
      interval: 1m
